/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#ifdef __WIN32__
#define UNITY_INCLUDE_SETUP_STUBS
#endif
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "../src/sw.h"
#include "testvector.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_MpAdd(void);
extern void test_MpSubTest(void);
extern void test_MpSubTestZeros(void);
extern void test_Mod(void);
extern void test_ModAdd(void);
extern void test_ModSub(void);
extern void test_MontMultiply1(void);
extern void test_MontMultiply2(void);
extern void test_MontMultiply3(void);
extern void test_AddCarry(void);
extern void test_ModExp(void);


/*=======Suite Setup=====*/
static void suite_setup(void)
{
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  suiteSetUp();
#endif
}

/*=======Suite Teardown=====*/
static int suite_teardown(int num_failures)
{
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  return suiteTearDown(num_failures);
#else
  return num_failures;
#endif
}

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  suite_setup();
  UnityBegin("test/sw_test.c");
  RUN_TEST(test_MpAdd, 5);
  RUN_TEST(test_MpSubTest, 19);
  RUN_TEST(test_MpSubTestZeros, 31);
  RUN_TEST(test_Mod, 43);
  RUN_TEST(test_ModAdd, 53);
  RUN_TEST(test_ModSub, 63);
  RUN_TEST(test_MontMultiply1, 78);
  RUN_TEST(test_MontMultiply2, 91);
  RUN_TEST(test_MontMultiply3, 104);
  RUN_TEST(test_AddCarry, 117);
  RUN_TEST(test_ModExp, 128);

  return suite_teardown(UnityEnd());
}
